### ISSUE TITLE
Wrong Path On Windows

### ISSUE THREAD

**Issue by isonnymichael** [artistudioxyz/aspri#2]
After I tried to run the command `aspri --wp-plugin-build-check` I got the error:
```
2024/04/04 16:26:07 open C:\Users\isonn\Local Sites\fab\app\public\wp-content\plugins \floating-awesome-button/C:\Users\isonn\Local Sites\fab\app\public\wp-content\plugins\floating-awesome-button.php: The filename, directory name, or volume label syntax is incorrect.
```

It seems aspri can't detect the path correctly, especially on windows. The correct path should be `C:\Users\isonn\Local Sites\fab\app\public\wp-content\plugins \floating-awesome-button\floating-awesome-button.php`

**Comment by agung2001** [comment]
close the issue, PR been merged
